{% set name = "celerite2" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b6a7f5ca9403ae6640599bebaaafe2782b81a1653810b940f24a81988976f170

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - pybind11 >=2.4
    - setuptools_scm
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - celerite2

about:
  home: https://celerite2.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast and scalable Gaussian Processes in 1D
  doc_url: https://celerite2.readthedocs.io
  dev_url: https://github.com/exoplanet-dev/celerite2

extra:
  recipe-maintainers:
    - dfm
    - mwcraig
