{% set name = "celerite2" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7ebfdf5792c23b50c88c46625f8e16043ca215111fff919cb006e8ac50acf88b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - pybind11
    - setuptools_scm
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - celerite2

about:
  home: https://celerite2.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast and scalable Gaussian Processes in 1D
  doc_url: https://celerite2.readthedocs.io
  dev_url: https://github.com/exoplanet-dev/celerite2

extra:
  recipe-maintainers:
    - dfm
