{% set name = "celerite2" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 91a90900037ab6e179f653a12d8d0c49fef1d0e9292b0dd5d0aa40ba00018415

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - scikit-build-core                      # [build_platform != target_platform]
    - setuptools_scm                         # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [linux]
  host:
    - python
    - scikit-build-core
    - setuptools_scm
    - numpy
    - pybind11
    - pip
  run:
    - python
    - {{ pin_compatible("numpy") }}

test:
  imports:
    - celerite2

about:
  home: https://celerite2.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast and scalable Gaussian Processes in 1D
  doc_url: https://celerite2.readthedocs.io
  dev_url: https://github.com/exoplanet-dev/celerite2

extra:
  recipe-maintainers:
    - dfm
    - mwcraig
